programs:
  ls:
    cmd: "/usr/bin/ls -la"
    processes: 2
    umask: 022
    workingdir: /tmp
    autostart: true
    start_at_launch: true
    autorestart: unexpected
    exitcodes:
    - 0
    - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/ls.stdout
    stderr: /tmp/ls.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42