#cuando comento esto hace un exit del taskmaster preguntar a luis del comportamiento
programs:
  # example:
  #   command: "/usr/bin/python3  /workspaces/taskmaster/worker/worker.py"
  #   processes: 2
  #   start_at_launch: true
  #   restart_policy: "on_failure"
  #   expected_exit_codes:
  #     - 0
  #     - 2
  #   success_timeout: 5
  #   max_restarts: 3
  #   stop_signal: "SIGTERM"
  #   stop_timeout: 5
  #   discard_output: false
  #   stdout: "./worker.out"
  #   stderr: "./worker.err"
  #   env:
  #     APP_ENV: "production"
  #     DB_HOST: "localhost"
  #     DB_PORT: "5432"
  #   working_dir: "."
  #   umask: 027

  # working_dir_and_env:
  #   command: "/usr/bin/python3  /workspaces/taskmaster/worker/working_dir_and_env.py"
  #   processes: 1
  #   start_at_launch: true
  #   restart_policy: "on_failure"
  #   expected_exit_codes:
  #     - 0
  #     - 2
  #   success_timeout: 0
  #   max_restarts: 3
  #   stop_signal: "SIGTERM"
  #   stop_timeout: 5
  #   discard_output: false
  #   stdout: "./working_dir_and_env.out"
  #   stderr: "./working_dir_and_env.err"
  #   env:
  #     APP_ENV: "production"
  #     DB_HOST: "localhost"
  #     DB_PORT: "5432"
  #   working_dir: "/tmp"
  #   umask: 027

  # discard_output_example:
  #   command: "/usr/bin/python3  /workspaces/taskmaster/worker/worker.py"
  #   processes: 1
  #   start_at_launch: true
  #   restart_policy: "on_failure"
  #   expected_exit_codes:
  #     - 0
  #     - 2
  #   success_timeout: 5
  #   max_restarts: 3
  #   stop_signal: "SIGTERM"
  #   stop_timeout: 5
  #   discard_output: True


  # fails:
  #   command: "/usr/bin/python3  /workspaces/taskmaster/worker/fails.py"
  #   processes: 1
  #   start_at_launch: true
  #   restart_policy: "on_failure"
  #   expected_exit_codes:
  #     - 0
  #     - 2
  #   success_timeout: 5
  #   max_restarts: 3
  #   stop_signal: "SIGTERM"
  #   stop_timeout: 5
  #   discard_output: false
  #   stdout: "./fails.out"
  #   stderr: "./fails.err"
  #   env:
  #     APP_ENV: "production"
  #     DB_HOST: "localhost"
  #     DB_PORT: "5432"
  #   working_dir: "."
  # #   umask: 027

  # success_timeout:
  #   command: "/usr/bin/python3  /workspaces/taskmaster/worker/success_time_out.py"
  #   processes: 1
  #   start_at_launch: true
  #   restart_policy: "on_failure"
  #   expected_exit_codes:
  #     - 0
  #     - 2
  #   success_timeout: 5
  #   max_restarts: 3
  #   stop_signal: "SIGTERM"
  #   stop_timeout: 5
  #   stdout: "./success_timeout.out"
  #   stderr: "./success_timeout.err"
  #   umask: 027

  # fail_timeout:
  #   command: "/usr/bin/python3  /workspaces/taskmaster/worker/fail_time_out.py"
  #   processes: 1
  #   start_at_launch: true
  #   restart_policy: "on_failure"
  #   expected_exit_codes:
  #     - 0
  #     - 2
  #   success_timeout: 5
  #   max_restarts: 3
  #   stop_signal: "SIGTERM"
  #   stop_timeout: 5
  #   stdout: "./fail_time_out.out"
  #   stderr: "./fail_time_out.err"
  #   umask: 027


  takes_too_long_to_die:
    command: "/usr/bin/python3  /workspaces/taskmaster/worker/takes_too_long_to_die.py"
    processes: 1
    start_at_launch: true
    restart_policy: "on_failure"
    expected_exit_codes:
      - 0
      - 2
    success_timeout: 5
    max_restarts: 3
    stop_signal: "SIGTERM"
    stop_timeout: 5
    stdout: "./takes_too_long_to_die.out"
    stderr: "./takes_too_long_to_die.err"
    umask: 027
